version: '1.0.{build}'
services:
  - postgresql
before_test:
  - cmd: SET PGUSER=postgres
  - cmd: SET PGPASSWORD=Password12!
  - cmd: PATH=C:\Program Files\PostgreSQL\9.6\bin\;C:\Program Files\nodejs;C:\Users\appveyor\AppData\roaming\npm;C:\Program Files (x86)\nodejs
  - cmd: psql -h 127.0.0.1 -p 5432 -c "DROP DATABASE IF EXISTS appveyor;" -U postgres
  - cmd: psql -h 127.0.0.1 -p 5432 -c "CREATE DATABASE appveyor;" -U postgres
environment:
  nodejs_version: "stable"
install:
  - ps: Install-Product node $env:nodejs_version
test_script:
  - node --version
  - npm --version
  - npm install
  - cmd: copy .env.appveyor .env
  - cmd: echo "This will be printed on the console"
  - cmd: npm run test:windows
build: off